# Generated by Django 4.0.3 on 2022-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('minimum_bid_price', models.PositiveIntegerField()),
                ('auction_end_date_time', models.DateTimeField()),
            ],
        ),
    ]
