# Generated by Django 4.0.3 on 2022-04-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_alter_listing_auction_end_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
